spring.application.name=backend
server.port=${PORT:8082}

# Database Configuration (MySQL)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/appointment_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:#Harsh2005}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Disable H2 console
spring.h2.console.enabled=false

# Allow cross origin requests for local react frontend and Render
spring.web.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173}
